spring.application.name=moviess

# ? DATABASE SERVER CONNECTION SETTINGS
# Maps to your local PostgreSQL instance on the default port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/cinekeep_db
spring.datasource.username=postgres
spring.datasource.password=2005
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? HIBERNATE JPA OBJECT-RELATIONAL MAPPING (ORM) CONFIGURATIONS
# Translates abstract data methods into optimized PostgreSQL dialect commands
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# Streams cleanly formatted SQL outputs directly to the system console trail for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081